### ISSUE TITLE
Clean unnecessary trailing 's's in admin page

### ISSUE THREAD

**Issue by Quicksaver** [marzeelabs/besugo#15]
The CMS script likes to add trailing 's's to labels, even to those that don't allow creating content in those collections. We should get rid of those, it's weird to see something like "Homes" or "Footers" when there are only one of each.

- [x] Get rid of trailing 's's through a jQuery inject (backport from https://github.com/marzeelabs/fesagency/issues/19)
- [ ] Find if there's a way to respond to CMS/React building the sidebar, so we can update the labels instantly without relying on DOM mutation observers.
- [x] Bonus: compile the js-yaml and jQuery scripts into a minified ```admin.min.js``` file.
- [ ] Double Bonus: compile js-yaml and jQuery from node dependencies.

**Comment by Quicksaver** [comment]
@pdsdesign when you get back, can you take a quick look at the slick component (slider) to see if it's displaying correctly? I cleaned up a lot of redundant code after importing it from node_modules and it seems to be working fine, but you know it better than I do, so just to make sure. 😃

**Comment by pdsdesign** [comment]
@Quicksaver Just checked, seems to be all good
