### ISSUE TITLE
Resolve (harmless) console error in fish shell

### ISSUE THREAD

**Issue by Quicksaver** [marzeelabs/besugo#37]
When watching for files, change app.scss:
```
change:scss/app.scss
nvm is not compatible with the "PREFIX" environment variable: currently set to "/usr/local"
Run `unset PREFIX` to unset it.
exit code: 11
Bass encountered an error!
```

Files still compile though, and only happens with a fish shell apparently (or at least something derived from it, a wrapper maybe?).

**Comment by jolidog** [comment]
Let's mark this as closed, new start mode hides this warning.
