### ISSUE TITLE
Switch to Yarn

### ISSUE THREAD

**Issue by pvhee** [marzeelabs/besugo#7]
* Use Yarn as our package manager 
* Wrap gulp tasks into yarn scripts and document. You'd build the site using `yarn build` rather than `gulp build`

**Comment by Quicksaver** [comment]
@pvhee to clarify, is the goal also to get rid of anything-gulp and use node scripts to feed yarn instead?

I.e. get rid of gulpfile.js and ```yarn start``` would call something like ```node start.js```, etc.

**Comment by Quicksaver** [comment]
Personally, I'd stay with gulp tasks at least for now. Rewritting them into node scripts / CL commands could be fun (at least from a learning point of view), but from what I'm seeing they would hardly save on dependencies and would take a lot more lines of code than we have now with gulp.
